name: Android Build (sm64ex)

on:
  push:
    branches: [appimage]
  pull_request:
    branches: [appimage]

jobs:
  build-android:
    name: Build sm64ex Android APK
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_NDK_HOME: ${{ github.workspace }}/android-sdk/ndk/25.2.9519653

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v3

    # Step 2: Set up Java, Android SDK, and NDK
    - name: Install Android SDK and NDK
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip openjdk-11-jdk wget
        wget https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip -O cmdline-tools.zip
        mkdir -p android-sdk/cmdline-tools
        unzip cmdline-tools.zip -d android-sdk/cmdline-tools
        yes | android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        yes | android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.0" "ndk;25.2.9519653"

    # Step 3: Build the sm64ex project using Gradle
    - name: Build sm64ex APK
      run: |
        mkdir -p build/android
        cd build/android
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
              -DANDROID_ABI=arm64-v8a \
              -DANDROID_PLATFORM=android-33 \
              -DCMAKE_BUILD_TYPE=Release \
              ../../
        make -j$(nproc)

    # Step 4: Package the APK
    - name: Assemble APK
      run: |
        cd build/android
        ./gradlew assembleRelease

    # Step 5: Upload the built APK as an artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: sm64ex-android-${{ github.run_number }}
        path: 'build/android/app/build/outputs/apk/release/*.apk'
